// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA39lidWQtvBQv_l6yi0SxU3-ayYg4giN0',
    appId: '1:131499170989:web:60f2c4eb50cbb7a3f93a24',
    messagingSenderId: '131499170989',
    projectId: 'pharmacy-system-4dba2',
    authDomain: 'pharmacy-system-4dba2.firebaseapp.com',
    storageBucket: 'pharmacy-system-4dba2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdGORnOPR33MOmg-67tzhQyDkyjKuv8g4',
    appId: '1:131499170989:android:daceb7d7fb473942f93a24',
    messagingSenderId: '131499170989',
    projectId: 'pharmacy-system-4dba2',
    storageBucket: 'pharmacy-system-4dba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFCJdd5C8SmvvXnQzLMKy4qFW0I-p_soc',
    appId: '1:131499170989:ios:187a59bf9ab5f9dcf93a24',
    messagingSenderId: '131499170989',
    projectId: 'pharmacy-system-4dba2',
    storageBucket: 'pharmacy-system-4dba2.firebasestorage.app',
    iosBundleId: 'com.example.pharmacySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFCJdd5C8SmvvXnQzLMKy4qFW0I-p_soc',
    appId: '1:131499170989:ios:187a59bf9ab5f9dcf93a24',
    messagingSenderId: '131499170989',
    projectId: 'pharmacy-system-4dba2',
    storageBucket: 'pharmacy-system-4dba2.firebasestorage.app',
    iosBundleId: 'com.example.pharmacySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA39lidWQtvBQv_l6yi0SxU3-ayYg4giN0',
    appId: '1:131499170989:web:5eeac7f300804b39f93a24',
    messagingSenderId: '131499170989',
    projectId: 'pharmacy-system-4dba2',
    authDomain: 'pharmacy-system-4dba2.firebaseapp.com',
    storageBucket: 'pharmacy-system-4dba2.firebasestorage.app',
  );
}
